"""make dates nullable for unplanned items

Revision ID: 499f96d0f469
Revises: cbf393309be2
Create Date: 2026-04-20 14:01:40.959114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499f96d0f469'
down_revision: Union[str, None] = 'cbf393309be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcements', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('milestones', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('tasks', 'planned_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('tasks', 'planned_end',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'planned_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tasks', 'planned_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('milestones', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('announcements', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
